S6 us20/admin details artwork
WildCodeSchool/2023-09-JS-Toulouse-666-Street-Art-Hunter pull request #39
Opened 2024-01-31 13:17 UTC by theonapoly

2024-02-02 14:09 UTC, Adri-bis approved these changes

2024-02-02 14:15 UTC, ArthurHtbk requested changes

2024-02-02 14:15 UTC, ArthurHtbk commented on frontend/src/pages/ArtworkOption/ArtworkOption.scss
> +        // border: 1px solid white;
😱

2024-02-05 10:56 UTC, ArthurHtbk requested changes
Attention, petit bout de code mort !

2024-02-05 10:56 UTC, ArthurHtbk commented on frontend/src/pages/Legal/Legal.scss
> +      // color: whitesmoke;
😱

2024-02-05 11:22 UTC, ArthurHtbk approved these changes

2024-02-05 11:23 UTC, merged